<Project>

  <!--
    Configuração comum a todos os projetos da solution Nexora.
    Ver ADR-036 (C#/.NET em solution única com Clean Architecture).
  -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <NoWarn>$(NoWarn);CA1000;CA1707;CA1711;CA1716;CA1848;CA1850;CA1859;CA1861;CA1873;CA5350;CS8602;CS8764;CS8765;NU1900;NU1901;NU1902;NU1903;NU1904</NoWarn>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <Company>Replay Studio</Company>
    <Product>Nexora</Product>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

</Project>
