using Awaken.Application.Common.Exceptions;
using Awaken.Application.Common.Interfaces;
using Awaken.Application.Exercises.Commands.ApproveExercise;
using Awaken.Domain.Entities.Exercises;
using Awaken.Domain.Repositories;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;

namespace Awaken.UnitTests.Exercises;

/// <summary>US-149 (R3.3) — curadoria manual: aprovar um exercício <c>pending_review</c> que atende
/// todos os critérios (RN-001), gravando quem revisou (RN-006).</summary>
public class ApproveExerciseCommandHandlerTests
{
    private readonly Mock<IExerciseCatalogRepository> _catalogRepository = new();
    private readonly Mock<IExerciseRawImportRepository> _rawImportRepository = new();
    private readonly Mock<ICurrentUserService> _currentUserService = new();
    private readonly Mock<IDateTimeService> _dateTimeService = new();
    private readonly Mock<IUnitOfWork> _unitOfWork = new();
    private readonly Mock<ILogger<ApproveExerciseCommandHandler>> _logger = new();

    private static readonly DateTime UtcNow = new(2026, 7, 5, 12, 0, 0, DateTimeKind.Utc);
    private static readonly Guid CuratorId = Guid.NewGuid();

    public ApproveExerciseCommandHandlerTests()
    {
        _dateTimeService.Setup(d => d.UtcNow).Returns(UtcNow);
        _currentUserService.Setup(c => c.UserId).Returns(CuratorId);
        _currentUserService.Setup(c => c.Email).Returns("curator@awaken.app");
    }

    private ApproveExerciseCommandHandler CreateHandler() => new(
        _catalogRepository.Object,
        _rawImportRepository.Object,
        _currentUserService.Object,
        _dateTimeService.Object,
        _unitOfWork.Object,
        _logger.Object);

    private static ExerciseCatalogSnapshot ValidSnapshot(Guid? rawImportId = null) => new(
        RawImportId: rawImportId,
        ProviderName: "local_files",
        ProviderExerciseId: "0001",
        ProviderVersion: null,
        NamePtBr: "Agachamento",
        NameOriginal: "Squat",
        Slug: "agachamento",
        DescriptionPtBr: "Descricao",
        InstructionsPtBr: ["Passo 1"],
        InstructionsOriginal: ["Step 1"],
        TipsPtBr: [],
        ExerciseType: "strength",
        MovementPattern: "squat",
        MovementFamily: "squat_family",
        Mechanic: "compound",
        ForceType: "push",
        PlaneOfMotion: "sagittal",
        Laterality: "bilateral",
        BodyPosition: "standing",
        BenchAngle: null,
        EquipmentCategory: "free_weight",
        LoadType: "free_weight",
        PrimaryRegion: "lower_body",
        DifficultyLevel: "intermediate",
        DifficultyRank: 3,
        TechnicalComplexity: 3,
        ImpactLevel: 2,
        Environment: "gym",
        RequiredEquipment: ["barbell"],
        PrimaryMuscleGroups: ["quadriceps"],
        SecondaryMuscleGroups: ["glutes"],
        BodyParts: ["legs"],
        JointStressTags: [],
        ContraindicationTags: [],
        LimitationBlockTags: [],
        PainBlockTags: [],
        GoalTags: ["maintenance"],
        RiskTags: [],
        AccessibilityTags: [],
        TaxonomySignals: [],
        MinExperienceLevel: "intermediate",
        SuitableForSedentary: false,
        SuitableForBeginner: false,
        SuitableForIntermediate: true,
        SuitableForAdvanced: true,
        IsCompound: true,
        IsUnilateral: false,
        IsAssisted: false,
        IsWeighted: true,
        RegressionExerciseIds: [],
        ProgressionExerciseIds: [],
        RelatedExerciseIds: [],
        VideoUrl: null,
        ImageUrl: null,
        GifUrl: "https://cdn.awaken.app/0001/360.gif",
        MediaLicenseInfo: null,
        SanitizationStatus: "pending_review",
        IsApprovedForWorkoutGeneration: false,
        Confidence: "high");

    [Fact]
    public async Task HandleApprovesExerciseAndRecordsReviewerWhenItMeetsAllCriteria()
    {
        var catalog = ExerciseCatalog.Create(ValidSnapshot(), UtcNow);
        catalog.SetAttributeContribution(
            ExerciseAttributeContribution.CreateAutoGenerated("strength", 2, 0, 0, 0, 0, 1), UtcNow);
        _catalogRepository.Setup(r => r.GetByIdAsync(catalog.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(catalog);

        var result = await CreateHandler().Handle(new ApproveExerciseCommand(catalog.Id), CancellationToken.None);

        catalog.IsApprovedForWorkoutGeneration.Should().BeTrue();
        catalog.SanitizationStatus.Should().Be("approved");
        catalog.ReviewedBy.Should().Be("curator@awaken.app");
        catalog.ReviewedAtUtc.Should().Be(UtcNow);
        result.Id.Should().Be(catalog.Id);
        result.Status.Should().Be("approved");
        result.IsApprovedForWorkoutGeneration.Should().BeTrue();
        _catalogRepository.Verify(r => r.Update(catalog), Times.Once);
        _unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task HandleAlsoMarksAssociatedRawImportAsApprovedWhenItExists()
    {
        var rawImport = ExerciseRawImport.CreateImported(
            "local_files", "0001", null, "{}", "imp_1", null, null, null, null, UtcNow);
        var catalog = ExerciseCatalog.Create(ValidSnapshot(rawImportId: rawImport.Id), UtcNow);
        catalog.SetAttributeContribution(
            ExerciseAttributeContribution.CreateAutoGenerated("strength", 2, 0, 0, 0, 0, 1), UtcNow);
        _catalogRepository.Setup(r => r.GetByIdAsync(catalog.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(catalog);
        _rawImportRepository.Setup(r => r.GetByIdAsync(rawImport.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(rawImport);

        await CreateHandler().Handle(new ApproveExerciseCommand(catalog.Id), CancellationToken.None);

        rawImport.Status.Should().Be(ExerciseRawImportStatus.Approved);
        _rawImportRepository.Verify(r => r.Update(rawImport), Times.Once);
    }

    [Fact]
    public async Task HandleThrowsWhenExerciseHasSanitizationIssuesPreventingApproval()
    {
        // RN-001: sem equipamento mapeado -> SanitizationIssues nao vazio -> CanBeApproved()==false.
        var catalog = ExerciseCatalog.Create(ValidSnapshot() with { RequiredEquipment = [] }, UtcNow);
        catalog.SetAttributeContribution(
            ExerciseAttributeContribution.CreateAutoGenerated("strength", 2, 0, 0, 0, 0, 1), UtcNow);
        _catalogRepository.Setup(r => r.GetByIdAsync(catalog.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(catalog);

        var act = async () => await CreateHandler().Handle(new ApproveExerciseCommand(catalog.Id), CancellationToken.None);

        await act.Should().ThrowAsync<InvalidOperationException>();
        catalog.IsApprovedForWorkoutGeneration.Should().BeFalse();
        _unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task HandleThrowsNotFoundWhenExerciseDoesNotExist()
    {
        var missingId = Guid.NewGuid();
        _catalogRepository.Setup(r => r.GetByIdAsync(missingId, It.IsAny<CancellationToken>()))
            .ReturnsAsync((ExerciseCatalog?)null);

        var act = async () => await CreateHandler().Handle(new ApproveExerciseCommand(missingId), CancellationToken.None);

        await act.Should().ThrowAsync<NotFoundException>();
    }
}
