using Awaken.Domain.Common;

namespace Awaken.Domain.Entities.Exercises;

public class ExerciseAttributeContribution : BaseEntity
{
    public Guid ExerciseCatalogId { get; private set; }
    public string PrimaryAttribute { get; private set; } = string.Empty;
    public int StrengthXp { get; private set; }
    public int AgilityXp { get; private set; }
    public int EnduranceXp { get; private set; }
    public int VitalityXp { get; private set; }
    public int FocusXp { get; private set; }
    public int WisdomXp { get; private set; }
    public bool IsAutoGenerated { get; private set; }
    public string? ReviewedBy { get; private set; }
    public DateTime? ReviewedAtUtc { get; private set; }

    private ExerciseAttributeContribution() { }

    public static ExerciseAttributeContribution CreateAutoGenerated(
        string primaryAttribute,
        int strengthXp,
        int agilityXp,
        int enduranceXp,
        int vitalityXp,
        int focusXp,
        int wisdomXp)
    {
        var contribution = new ExerciseAttributeContribution
        {
            PrimaryAttribute = primaryAttribute,
            StrengthXp = strengthXp,
            AgilityXp = agilityXp,
            EnduranceXp = enduranceXp,
            VitalityXp = vitalityXp,
            FocusXp = focusXp,
            WisdomXp = wisdomXp,
            IsAutoGenerated = true,
        };

        if (!contribution.IsValidForApprovedExercise())
            throw new InvalidOperationException(
                "Exercise attribute contribution must include wisdom and one non-wisdom attribute."
            );

        return contribution;
    }

    public void ApplyAutoGenerated(
        string primaryAttribute,
        int strengthXp,
        int agilityXp,
        int enduranceXp,
        int vitalityXp,
        int focusXp,
        int wisdomXp,
        DateTime utcNow)
    {
        PrimaryAttribute = primaryAttribute;
        StrengthXp = strengthXp;
        AgilityXp = agilityXp;
        EnduranceXp = enduranceXp;
        VitalityXp = vitalityXp;
        FocusXp = focusXp;
        WisdomXp = wisdomXp;
        IsAutoGenerated = true;
        UpdatedAtUtc = utcNow;

        if (!IsValidForApprovedExercise())
            throw new InvalidOperationException(
                "Exercise attribute contribution must include wisdom and one non-wisdom attribute."
            );
    }

    public bool IsValidForApprovedExercise()
    {
        if (string.Equals(PrimaryAttribute, "wisdom", StringComparison.OrdinalIgnoreCase))
            return false;

        if (WisdomXp < 1)
            return false;

        return StrengthXp > 0 || AgilityXp > 0 || EnduranceXp > 0 || VitalityXp > 0 || FocusXp > 0;
    }
}
