using Awaken.Domain.Entities.Exercises;
using Awaken.Domain.Services.Quests;
using FluentAssertions;

namespace Awaken.UnitTests.Quests;

public class ExerciseScoringEngineTests
{
    // GoalProfile.ExerciseGoalTags used by the engine:
    //   gain_muscle   → ["strength", "hypertrophy"]
    //   fat_loss      → ["fat_loss", "conditioning", "maintenance"]
    //   more_strength → ["strength"]

    private static ExerciseCatalog BuildExercise(
        string providerExerciseId = "0001",
        string minExperienceLevel = "beginner",
        int difficultyRank = 1,
        int impactLevel = 1,
        int technicalComplexity = 1,
        bool isWeighted = false,
        List<string>? goalTags = null,
        List<string>? primaryMuscleGroups = null,
        string movementPattern = "push",
        string? primaryAttribute = null,
        int strengthXp = 0,
        int enduranceXp = 0,
        int agilityXp = 0,
        int vitalityXp = 0,
        int focusXp = 0)
    {
        var snapshot = new ExerciseCatalogSnapshot(
            RawImportId: null,
            ProviderName: "test",
            ProviderExerciseId: providerExerciseId,
            ProviderVersion: null,
            NamePtBr: $"Exercicio {providerExerciseId}",
            NameOriginal: $"Exercise {providerExerciseId}",
            Slug: $"exercicio-{providerExerciseId}",
            DescriptionPtBr: "Descricao",
            InstructionsPtBr: ["Passo 1"],
            InstructionsOriginal: ["Step 1"],
            TipsPtBr: [],
            ExerciseType: "strength",
            MovementPattern: movementPattern,
            MovementFamily: "press",
            Mechanic: "compound",
            ForceType: "push",
            PlaneOfMotion: "sagittal",
            Laterality: "bilateral",
            BodyPosition: "standing",
            BenchAngle: null,
            EquipmentCategory: "bodyweight",
            LoadType: "bodyweight",
            PrimaryRegion: "upper_body",
            DifficultyLevel: minExperienceLevel,
            DifficultyRank: difficultyRank,
            TechnicalComplexity: technicalComplexity,
            ImpactLevel: impactLevel,
            Environment: "home",
            RequiredEquipment: [],
            PrimaryMuscleGroups: primaryMuscleGroups ?? ["chest"],
            SecondaryMuscleGroups: [],
            BodyParts: ["chest"],
            JointStressTags: [],
            ContraindicationTags: [],
            LimitationBlockTags: [],
            PainBlockTags: [],
            GoalTags: goalTags ?? [],
            RiskTags: [],
            AccessibilityTags: [],
            TaxonomySignals: [],
            MinExperienceLevel: minExperienceLevel,
            SuitableForSedentary: true,
            SuitableForBeginner: true,
            SuitableForIntermediate: true,
            SuitableForAdvanced: true,
            IsCompound: false,
            IsUnilateral: false,
            IsAssisted: false,
            IsWeighted: isWeighted,
            RegressionExerciseIds: [],
            ProgressionExerciseIds: [],
            RelatedExerciseIds: [],
            VideoUrl: null,
            ImageUrl: null,
            GifUrl: null,
            MediaLicenseInfo: null,
            SanitizationStatus: "approved",
            IsApprovedForWorkoutGeneration: true,
            Confidence: "high");

        var exercise = ExerciseCatalog.Create(snapshot, DateTime.UtcNow);

        if (primaryAttribute is not null)
        {
            var s = string.Equals(primaryAttribute, "strength", StringComparison.OrdinalIgnoreCase) ? Math.Max(strengthXp, 1) : strengthXp;
            var e = string.Equals(primaryAttribute, "endurance", StringComparison.OrdinalIgnoreCase) ? Math.Max(enduranceXp, 1) : enduranceXp;
            var a = string.Equals(primaryAttribute, "agility", StringComparison.OrdinalIgnoreCase) ? Math.Max(agilityXp, 1) : agilityXp;
            var v = string.Equals(primaryAttribute, "vitality", StringComparison.OrdinalIgnoreCase) ? Math.Max(vitalityXp, 1) : vitalityXp;
            var f = string.Equals(primaryAttribute, "focus", StringComparison.OrdinalIgnoreCase) ? Math.Max(focusXp, 1) : focusXp;

            exercise.SetAttributeContribution(ExerciseAttributeContribution.CreateAutoGenerated(
                primaryAttribute, s, a, e, v, f, wisdomXp: 1), DateTime.UtcNow);
        }

        return exercise;
    }

    private static ExerciseScoringContext BuildContext(
        string? goal = null,
        string effectiveExperienceLevel = "intermediate",
        int availableMinutesPerWorkout = 30,
        Dictionary<string, int>? userAttributes = null) =>
        new(goal, effectiveExperienceLevel, availableMinutesPerWorkout,
            userAttributes ?? new Dictionary<string, int>());

    // --- goalAffinityScore ---

    [Fact]
    public void GoalAffinity_IsHigh_WhenExerciseTagMatchesGoalProfile()
    {
        // gain_muscle GoalProfile.ExerciseGoalTags = ["strength", "hypertrophy"]
        var exercise = BuildExercise(goalTags: ["strength"]);
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(goal: "gain_muscle"));

        scores[0].GoalAffinityScore.Should().Be(1.0);
    }

    [Fact]
    public void GoalAffinity_IsZero_WhenExerciseTagDoesNotMatchGoalProfile()
    {
        // gain_muscle expects "strength" or "hypertrophy"; "conditioning" is not in that list
        var exercise = BuildExercise(goalTags: ["conditioning"]);
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(goal: "gain_muscle"));

        scores[0].GoalAffinityScore.Should().Be(0.0);
    }

    [Fact]
    public void GoalAffinity_IsNeutral_WhenExerciseHasNoGoalTags()
    {
        var exercise = BuildExercise(goalTags: []);
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(goal: "gain_muscle"));

        scores[0].GoalAffinityScore.Should().Be(0.5);
    }

    // --- safetyScore ---

    [Fact]
    public void SafetyScore_IsHigh_WhenLowImpactAndLowComplexity()
    {
        var exercise = BuildExercise(impactLevel: 1, technicalComplexity: 0);
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext());

        scores[0].SafetyScore.Should().Be(1.0);
    }

    [Fact]
    public void SafetyScore_IsLow_WhenHighImpactAndHighComplexity()
    {
        var exercise = BuildExercise(impactLevel: 5, technicalComplexity: 5);
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext());

        scores[0].SafetyScore.Should().Be(0.0);
    }

    // CA-001 (US-151): exercício mais seguro vence sobre similar com mesma afinidade de objetivo.
    [Fact]
    public void CA001_SaferExercise_RanksHigher_WhenGoalAffinityIsSimilar()
    {
        var safe = BuildExercise(
            providerExerciseId: "safe",
            goalTags: ["strength"],
            impactLevel: 1, technicalComplexity: 0);

        var unsafe_ = BuildExercise(
            providerExerciseId: "unsafe",
            goalTags: ["strength"],
            impactLevel: 5, technicalComplexity: 5);

        var scores = ExerciseScoringEngine.Score([unsafe_, safe], BuildContext(goal: "gain_muscle"));

        scores[0].Exercise.ProviderExerciseId.Should().Be("safe");
    }

    // --- levelMatchScore ---

    [Fact]
    public void LevelMatch_IsPerfect_WhenExerciseLevelEqualsEffectiveLevel()
    {
        var exercise = BuildExercise(minExperienceLevel: "intermediate");
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(effectiveExperienceLevel: "intermediate"));

        scores[0].LevelMatchScore.Should().Be(1.0);
    }

    [Fact]
    public void LevelMatch_IsReduced_WhenLevelsDiffer()
    {
        var exercise = BuildExercise(minExperienceLevel: "advanced");
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(effectiveExperienceLevel: "beginner"));

        scores[0].LevelMatchScore.Should().BeLessThan(1.0);
    }

    // --- timeFitScore ---

    [Fact]
    public void TimeFit_IsHigher_ForShorterExercise()
    {
        var shortEx = BuildExercise(providerExerciseId: "short", difficultyRank: 1, isWeighted: false);
        var longEx = BuildExercise(providerExerciseId: "long", difficultyRank: 3, isWeighted: true);

        var scores = ExerciseScoringEngine.Score([shortEx, longEx], BuildContext(availableMinutesPerWorkout: 30));

        var shortScore = scores.First(s => s.Exercise.ProviderExerciseId == "short").TimeFitScore;
        var longScore = scores.First(s => s.Exercise.ProviderExerciseId == "long").TimeFitScore;

        shortScore.Should().BeGreaterThan(longScore);
    }

    // --- targetAttributeScore (US-152) ---

    [Fact]
    public void TargetAttribute_IsMaximum_WhenGoalMatchesAndUserAttributeIsLow()
    {
        // gain_muscle TargetAttributes = strength, vitality, focus
        var exercise = BuildExercise(primaryAttribute: "strength", strengthXp: 10);
        var scores = ExerciseScoringEngine.Score(
            [exercise],
            BuildContext(goal: "gain_muscle", userAttributes: new() { ["strength"] = 1 }));

        scores[0].TargetAttributeScore.Should().Be(1.0);
    }

    [Fact]
    public void TargetAttribute_IsPartial_WhenGoalMatchesButAttributeIsNotLow()
    {
        var exercise = BuildExercise(primaryAttribute: "strength", strengthXp: 10);
        var scores = ExerciseScoringEngine.Score(
            [exercise],
            BuildContext(goal: "gain_muscle", userAttributes: new() { ["strength"] = 10 }));

        scores[0].TargetAttributeScore.Should().Be(0.5);
    }

    [Fact]
    public void TargetAttribute_IsPartial_WhenAttributeIsLowButNotAGoalTarget()
    {
        // fat_loss TargetAttributes: endurance, vitality, strength — NOT focus
        var exercise = BuildExercise(primaryAttribute: "focus", focusXp: 10);
        var scores = ExerciseScoringEngine.Score(
            [exercise],
            BuildContext(goal: "fat_loss", userAttributes: new() { ["focus"] = 1 }));

        scores[0].TargetAttributeScore.Should().Be(0.5);
    }

    [Fact]
    public void TargetAttribute_IsNeutral_WhenNoAttributeContributionSet()
    {
        var exercise = BuildExercise();
        var scores = ExerciseScoringEngine.Score([exercise], BuildContext(goal: "gain_muscle"));

        scores[0].TargetAttributeScore.Should().Be(0.5);
    }

    // RN-001 + RN-003 US-151: segurança domina sobre objetivo e atributo-alvo no desempate do score.
    [Fact]
    public void RN001_RN003_SafeExercise_RanksHigher_DespiteNoGoalOrAttributeBonus()
    {
        var safeNoGoal = BuildExercise(
            providerExerciseId: "safe_no_goal",
            impactLevel: 1, technicalComplexity: 0,
            goalTags: []);

        var unsafeWithBonus = BuildExercise(
            providerExerciseId: "unsafe_bonus",
            impactLevel: 5, technicalComplexity: 5,
            goalTags: ["strength"],
            primaryAttribute: "strength", strengthXp: 10);

        var scores = ExerciseScoringEngine.Score(
            [unsafeWithBonus, safeNoGoal],
            BuildContext(goal: "gain_muscle", userAttributes: new() { ["strength"] = 1 }));

        scores[0].Exercise.ProviderExerciseId.Should().Be("safe_no_goal");
    }

    // --- resultado ordenado ---

    [Fact]
    public void Score_ReturnsList_OrderedByStaticScoreDescending()
    {
        var high = BuildExercise(
            providerExerciseId: "high",
            goalTags: ["strength"],
            impactLevel: 1, technicalComplexity: 0,
            minExperienceLevel: "intermediate");

        var low = BuildExercise(
            providerExerciseId: "low",
            goalTags: [],
            impactLevel: 5, technicalComplexity: 5,
            minExperienceLevel: "advanced");

        var scores = ExerciseScoringEngine.Score(
            [low, high],
            BuildContext(goal: "gain_muscle", effectiveExperienceLevel: "intermediate"));

        scores[0].Exercise.ProviderExerciseId.Should().Be("high");
    }

    // --- US-152: mapeamento objetivo → atributos-alvo ---

    [Fact]
    public void US152_GoalFatLoss_TargetsEnduranceNotFocus()
    {
        var enduranceEx = BuildExercise(primaryAttribute: "endurance", enduranceXp: 10);
        var focusEx = BuildExercise(providerExerciseId: "0002", primaryAttribute: "focus", focusXp: 10);

        var ctx = BuildContext(goal: "fat_loss");
        var enduranceScore = ExerciseScoringEngine.Score([enduranceEx], ctx)[0].TargetAttributeScore;
        var focusScore = ExerciseScoringEngine.Score([focusEx], ctx)[0].TargetAttributeScore;

        enduranceScore.Should().BeGreaterThan(focusScore);
    }

    [Fact]
    public void US152_GoalMuscleGain_TargetsStrengthNotAgility()
    {
        var strengthEx = BuildExercise(primaryAttribute: "strength", strengthXp: 10);
        var agilityEx = BuildExercise(providerExerciseId: "0002", primaryAttribute: "agility", agilityXp: 10);

        var ctx = BuildContext(goal: "gain_muscle");
        var strengthScore = ExerciseScoringEngine.Score([strengthEx], ctx)[0].TargetAttributeScore;
        var agilityScore = ExerciseScoringEngine.Score([agilityEx], ctx)[0].TargetAttributeScore;

        strengthScore.Should().BeGreaterThan(agilityScore);
    }

    [Fact]
    public void US152_TargetAttribute_UsesSecondaryAttributeContribution_WhenPrimaryDoesNotMatch()
    {
        var enduranceEx = BuildExercise(
            primaryAttribute: "agility",
            agilityXp: 1,
            enduranceXp: 10);

        var scores = ExerciseScoringEngine.Score(
            [enduranceEx],
            BuildContext(goal: "gain_muscle", userAttributes: new() { ["endurance"] = 1, ["agility"] = 10 }));

        scores[0].TargetAttributeScore.Should().BeGreaterThan(0.0);
    }
}
