// <auto-generated />
using System;
using Awaken.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Awaken.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AwakenDbContext))]
    [Migration("20260628030000_AddRecentDailyPenaltyQuestDateToHunterProgression")]
    partial class AddRecentDailyPenaltyQuestDateToHunterProgression
    {
    }
}
